spring:
  datasource:
    url: jdbc:mysql://13.125.132.172:3306/balance-debate?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  session:
    store-type: jdbc

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false

server:
  servlet:
    session:
      timeout: 180d